#if !(defined(GO) && defined(GOM) && defined(GO2) && defined(DATA))
#error Meh....
#endif

GO(posix_spawn, iFpppppp)
GO(posix_spawnattr_destroy, iFp)
GO(posix_spawnattr_getflags, iFpp)
GO(posix_spawnattr_getpgroup, iFpp)
GO(posix_spawnattr_getschedparam, iFpp)
GO(posix_spawnattr_getschedpolicy, iFpp)
GO(posix_spawnattr_getsigdefault, iFpp)
GO(posix_spawnattr_getsigmask, iFpp)
GO(posix_spawnattr_init, iFp)
GO(posix_spawnattr_setflags, iFpw)
GO(posix_spawnattr_setpgroup, iFpi)
GO(posix_spawnattr_setschedparam, iFpp)
GO(posix_spawnattr_setschedpolicy, iFpi)
GO(posix_spawnattr_setsigdefault, iFpp)
GO(posix_spawnattr_setsigmask, iFpp)
GO(posix_spawn_file_actions_addchdir_np, iFpp)
GO(posix_spawn_file_actions_addclose, iFpi)
GO(posix_spawn_file_actions_adddup2, iFpii)
GO(posix_spawn_file_actions_addfchdir_np, iFpi)
GO(posix_spawn_file_actions_addopen, iFpipiu)
GO(posix_spawn_file_actions_destroy, iFp)
GO(posix_spawn_file_actions_init, iFp)
GO(posix_spawnp, iFpppppp)
